### ISSUE TITLE
configuration name is not consistency 

### ISSUE THREAD

**Issue by kevindiu** [yahoojapan/authorization-proxy#44]
Configuration name should be `_` separated or by letter case?

https://github.com/yahoojapan/authorization-proxy/blob/1360c02583f954790106fb51f367723d4d034239/config/config.go#L63

https://github.com/yahoojapan/authorization-proxy/blob/1360c02583f954790106fb51f367723d4d034239/config/config.go#L137

**Comment by WindzCUHK** [comment]
related: https://github.com/yahoojapan/athenz-client-sidecar/issues/34#issue-571814316

`roletoken` => `role_token`
https://github.com/yahoojapan/authorization-proxy/blob/e500d8c4977c83821434199f6d5001b815a86b4a/config/config.go#L172-L173
